spring:
  application:
    name: bootcamp_new_thinkers

  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: ${database_username}
    password: ${database_password}
    driver-class-name: oracle.jdbc.OracleDriver
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect # Tive problema nesse dialect do demonio - Lembrar de sempre colocar generico sem especificar a versão.